### ISSUE TITLE
Make BRAF related changes to user manual

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#1465]
@NerdyGirl537 wrangled some client feedback out of Team BRAF because she is a national treasure. I'm rolling the specific points from their doc into an omnibus thread that we can break things out from, but calling this futuretech for now so it doesn't interfere with any of the current stuff. Keeping in mind that this is more or less straight from their feedback and does not reflect a planned implementation or set of fixes, here's what they told us:

* `Add to Call LIst` in Event Log doesn't work/noops
* "When we enter callers, sometimes they don't get put on our call list -- or even if they are on the list one day, when we go back into DARIA they are not on the call list."
* Change footer link from gotfreefax to hellofax.com (CF note: probably can set this as an admin config)
* Delete button needs more explanation - suggested language change of "delete this patient record", and some clarity that it doesn't indicate that a duplicate record exists to avoid accidental nuking
* Requested a way to identify whether a patient is a duplicate record or not. Identified a pain point around same-patient-different-pregnancy and same-pregnancy-multiple-clinics situations
* Requested a patient merger function to consolidate two records (CF: :| )
* When using the `Enable NAF only` selector, it can be difficult to see the grayed out of non-NAF clinics, can the shading be more obvious?
* "Can we control when data is archived? We want access much longer, at least more than a year. So at the end of the fiscal year when we are trying to get some statistics we can actually lookat the person's intake record when needed."
* Requested a reminder to have CMs ask patients to spell their names (CF: this strikes me as a fund training problem but am interested in whether this is a pain point for others) 
* Requested way to ID a patient's phone as a cell or a landline - BRAF texts
* Requested way to add whether or not someone has had an ultrasound
* Requested field for appointment time (CF: I would want to have an EXTREMELY good reason for this)
* Requested changing label to referred by to something more readable - something like "How did caller hear about fund?"
* Requested putting "Another abortion fund" at the top of the referred by list since it's the most frequent for them
* Requested additional referred by fields. Config-able?
* Requested pledge forms generatable by DARIA. (CF: This is something that's been on the futuretech list for awhile, although not sure I've made an issue for it.)
* CSV report: They asked for the ability to see notes. (CF: This is a no-go for a lot of reasons laid out in our guidance doc.)
* Requested the ability to pull a date range for report (CF: no dice)

**Comment by alisonnjones** [comment]
Here are some preliminary thoughts re: prioritization 

**Let's follow up on these technical fixes and start new issue in Github (HIGH PRIORITY)-** 
Add to Call LIst in Event Log doesn't work/noops 
Change footer link from gotfreefax to hellofax.com (CF note: probably can set this as an admin config)
Requested way to add whether or not someone has had an ultrasoundRequested way to ID a patient's Requested changing label to referred by to something more readable - something like "How did caller hear about fund?"
Requested additional referred by fields. Config-able?
phone as a cell or a landline - BRAF texts (med to long-term)

**Let's follow up and find out specific examples of when this has happened and then figure out if we want to move forward (MEDIUM PRIORITY)-** 
"When we enter callers, sometimes they don't get put on our call list -- or even if they are on the list one day, when we go back into DARIA they are not on the call list."
"Can we control when data is archived? We want access much longer, at least more than a year. So at the end of the fiscal year when we are trying to get some statistics we can actually look at the person's intake record when needed."

**Update training manual with information explaining (HIGH PRIORITY)-**
Delete button needs more explanation - suggested language change of "delete this patient record", and some clarity that it doesn't indicate that a duplicate record exists to avoid accidental nuking 
Requested a way to identify whether a patient is a duplicate record or not. Identified a pain point around same-patient-different-pregnancy and same-pregnancy-multiple-clinics situations
Requested a reminder to have CMs ask patients to spell their names (CF: this strikes me as a fund training problem but am interested in whether this is a pain point for others)
Requested field for appointment time (CF: I would want to have an EXTREMELY good reason for this - BRAF should use notes for this function and train vols to do so)

**Parking lot for future discussion (LOW PRIORITY)**
When using the Enable NAF only selector, it can be difficult to see the grayed out of non-NAF clinics, can the shading be more obvious?
Requested putting "Another abortion fund" at the top of the referred by list since it's the most frequent for them
Requested pledge forms generatable by DARIA. (CF: This is something that's been on the futuretech list for awhile, although not sure I've made an issue for it.)

The rest have been deleted because they are no-gos. If BRAF wants to discuss the argument for them more, that's fine and we can record it in the list. But, we will definitely not be moving forward with those items in the near future.

**Comment by lwaldsc** [comment]
Before we make any movement, I would also want more information on:

"Can we control when data is archived? We want access much longer, at least more than a year. So at the end of the fiscal year when we are trying to get some statistics we can actually look at the person's intake record when needed."

Kat and others have thought long and hard around archiving policy, so I'd like a lot more specifics on why patients shouldn't be archived as is presently done.

Also a Nope on appointment time slot but willing to listen if they have a really compelling reason.

**Comment by colinxfleming** [comment]
Have moved the high priority items into their own github issues

**Comment by colinxfleming** [comment]
made a few extra issues. The remaining issues in here are all admin manual changes.

**Comment by colinxfleming** [comment]
declaring victory on this since we've done the bulk of it and the rest haven't been issues or have beensolved with training
