### ISSUE TITLE
Let's talk about whether installing some limited js framework is a good idea

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#1752]
I am admittedly starting from a place where I don't want to do this, but I think that the patient edit view is pretty complicated and I think we might benefit from some one-way state management of the variety that stimulus or react provides. Now that we are a webpack operation I think this would be much easier to maintain, and the fact is that stuff like `patients/update.js.erb` is really, really ugly and unfun to work with and test.

To be clear, I am interested in augmenting our HTML, not switching to a whole-hog single-page app. But I also think that moderating our approach to this some 

Some benefits off the top of my head of going with more JS in the frontend:
* state management gets easier! patients/update.js.erb is doing a LOT of work.
* frankly, more javascript work; JS is a language that most of our new volunteers write and this is an opportunity to do work on that front

Some potential drawbacks:
* app becomes harder to troubleshoot
* javascript ecosystem is scary and this is throwing javascript at a problem
* people are starting to write component libraries for rails, so, like, nonzero chance this isn't even a problem in rails 6.1?

If you have strong opinions about this, I am extremely interested in hearing them!

**Comment by tingaloo** [comment]
Since we have webpacker in place, these guys open up https://github.com/rails/webpacker#integrations.

[React](https://github.com/facebook/react): Safe choice since it is widely adopted all around. (was thinking of other funds adopting the app).

[Stimulus](https://github.com/stimulusjs/stimulus): It looks really stable but neglected (The copyright on the github page has not been updated.)

[vuejs](https://github.com/vuejs/vue): i heard is balanced and has good traction. Can build components and scale.

[angular](https://github.com/angular/angular): Potential overkill, 2 frameworks is a bit much.

[npm Trends
](https://www.npmtrends.com/@angular/core-vs-vue-vs-react-vs-@stimulus/core) to give insight on popularity.

On the context of DCAF itself, html erbs can be swapped out with Stimulus. It feels closer to rails adopting state lifecycles of modern frameworks.

React or vuejs are great for using the modern component methodology. We would need to gut most of our existing ```js.erb``` for consistency.

I am kind of biased on vuejs because it is a js framework i look forward to learning. I leave these options based on what we have. Webpacker is constantly updating, which follows the same cadence as react and vuejs. Definitely open for conversation on this one.

**Comment by colinxfleming** [comment]
Thank you very much for the great overview of potential solutions to this problem! My inclinations are toward stimulus (rails-y, stable, not very intrusive) or react (heavy, but extremely widely adopted). I think vue is a tough sell because it's not as widely understood, so we'd all have to learn it; angular I agree is much too heavy for what we're trying to do, and I've honestly never been able to figure it out.

@tingaloo assuming that we're only doing this for the patient edit view for now, how much of our existing controller architecture would we have to gut if we moved to react? It doesn't seem like we'd have to really dismantle things apart if we did stimulus; my sense is that we would if we adopted react.

Our choice might be wide adoption in react vs basically having something that supplements our existing code in stimulus. My inclination is to go with convention to widen our pool of potential contributors, and also doing stuff that makes us enjoy working in daria's codebase, because this should be fun. I don't know which option that leads us to but it might be react.

**Comment by tingaloo** [comment]
I'll give this a shot with react, i'll push a WIP PR with the amount of effort with gutting tests/controller.

**Comment by colinxfleming** [comment]
To close some of the loop on this:

* Before we do any real work we have to get bootstrap into webpacker at a minimum; getting stuff out of sprockets is nice
* We only really do fancy state management in two spots: the CM dashboard and the call lists. Those are good candidates for js
* let's try react on the patient edit page and see what problems we run into. (early research from @tingaloo suggests that i18n and some of our more infrequent patient object methods might be tough.)

**Comment by colinxfleming** [comment]
There are a few other tough things we gotta sort out:
* i18n handling (probably an argument for stimulus as the framework, though more people know react and that matters a ton to us)
* js.erb handling (controllers do a lot of heavy js lifting now; tbh this causes us all sorts fo problems)
* rails might be adopting limited components sometime soonish, does that influence our plan here? (probably not because a lot of our new developers speak js and not ruby)

**Comment by colinxfleming** [comment]
also, there's a lot of lifting currently done by model methods (LastMenstrualPeriodMeasureable for example), and dealing with those will be difficult.

**Comment by tingaloo** [comment]
It's a lot of work and would be an ongoing war to integrate both of them. More so have developers comfortable both with Rails and React.

Maybe there's a better way to make use of that effort like making an independent backend API?

**Comment by colinxfleming** [comment]
I think the ship has probably sailed on this one; closing as a wontfix for now
