### ISSUE TITLE
Add multifactor authentication

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2003]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Up to this point we've taken advantage of googly account security. I looked pretty hard and we unfortunately can't make people have 2fa on their google accounts. We can require general 2fa for all accounts, though, or require it for password entry, or just have it in general. (We should start by having it in general probably.)

* **What feature or behavior is this required for?**

Better app security since we're handling so much pii!

* **How could we solve this issue? (Not knowing is okay!)**

very carefully! @BintLopez has been doing some thinking about this over in lockbox town, so hopefully she'll have some insight to add here. (Step 1 of this process should be @BintLopez writing up their implementation on Lockbox and giving us some sense of what was easy, what sucked, and how their userbase handled it.)

I think our ideal outcome is:
* Admins can turn on 2fa for people in their org, on a per-user basis
* Users can turn it on for themselves if they want
* At a minimum, auth by sms; optionally stuff like apps and yubikeys and email maybe etc. (we have a twilio and sendgrid account and can provide keys easily)

I think that should square us away and put us in a good place?

* **Anything else?**

not currently!

**Comment by BintLopez** [comment]
This is the gem that I'm using and working through:  https://github.com/twilio/authy-devise

**Comment by colinxfleming** [comment]
okay, a writeup of the outcomes here is overdue from me, I think. Here it am:

This ticket should be considered done when:
* individual users can turn on 2fa on their profile pages and go thru a flow to set it up
* the users index page has a '2FA on/2FA off' badge
* when 2fa for a user is turned on, it should take them through a regular 2fa flow and prevent them from logging in if it 
fails

Other notes: 
* I think I have a preference for app based over SMS based all things being equal but if one is significantly easier than the other let's do the easy one
* I imagine there's a devise extension that will do this kinda thing, as this isn't exactly a unique problem to us
* I'm okay with spending money on a service, whether that be an authy fee or a twilio account or whatever, please let me know

**Comment by djohnston32** [comment]
Unfortunately the Authy API is being deprecated in favor of the new Twilio Verify API, so [authy-devise](https://github.com/twilio/authy-devise) is no longer an option. The authy-devise readme suggests a similar verify-devise plugin was once in development, but it's unclear if that's still the case. I reached out to Twilio support to confirm. Without that gem, there doesn't appear to be a well-maintained option that gives us all of 1) integrating well with devise, 2) providing robust support for a variety of channel types, 3) naturally supporting the most common two-step UI for MFA. 

If the [pricing](https://www.twilio.com/verify/pricing) is acceptable, [Twilio Verify](https://www.twilio.com/docs/verify) seems like the best option even if a helper gem isn't in development. We’d have to handle integrating it with devise ourselves, but it seems to make everything else relatively easy. It handles generating/storing codes, rate limiting, and other things itself and the documentation seems solid at a glance.

[devise-two-factor](https://github.com/tinfoil/devise-two-factor) is another option. It gives you a lot less out of the box, but it doesn't incur any costs on its own and it looks relatively straightforward to set up with app-based authentication. The downside is it looks like it takes quite a bit of wrangling to get it to do a standard two-step login process (see [this example](https://www.jamesridgway.co.uk/implementing-a-two-step-otp-u2f-login-workflow-with-rails-and-devise/)), and with SMS we'd have to handle generating and sending codes ourselves. It still gets occasional maintenance updates but given that it seems most other devise two factor gems appear to have stopped development, I'm not sure how long that will last.

**Comment by colinxfleming** [comment]
I think I'm willing to throw money at this if it does yield a less-maintenance or better experience/result (or if they manage more of it). Our userbase isn't big so 5c isn't problematic (though it is annoying, ha). I think if that seems like an effective path, let me know and I'll start a service - we have an org twilio account we can use for this I believe.

**Comment by djohnston32** [comment]
I definitely lean towards Verify. One question I think will help: do you think it's likely you'll want to add [any other channels](https://www.twilio.com/docs/verify/authentication-channels) beyond app-based (TOTP) in the future?

I think devise-two-factor would be faster and cheaper to get set up initially for app-based 2FA only (after more research I think I overstated the UI challenges above). But Verify has a clear advantage if you think it's likely you'll want to add any other channels. devise-two-factor is not much help with SMS for example. devise-two-factor also has all of 2 commits in the last 6 months, so the risk of maintenance problems in the future seems higher.

**Comment by colinxfleming** [comment]
I think my ideal world is that we offer people sms/email/app, though frankly I could live without app! I think most of our userbase is most likely to be SMS/email friendly but might be less comfortable with an app 2fa thing, though I would like to offer that option. I think based on that analysis twilio verify seems like an increasingly good option. 

@lomky do you have a strong opinion here? does that seem right to me?

**Comment by lomky** [comment]
Concur it feels like a trivial cost for our volume. I have the same instincts for the channels - our user base will be familiar with SMS & email MFA from their banks but plausibly won't have an app, but _I_ would want an app!

**Comment by djohnston32** [comment]
Cool! In the meantime I've been putting together a rough outline:

## UI
### Registration
- On My Profile page (`/users/edit`):
  - a section for multifactor which lists existing enabled factors
  - a button to add a new factor, which will go to a new factor registrations page
  - a button to disable MFA, if currently enabled
- New factor registration page
  - dropdown for selecting a type (SMS/Email/App)
  - based on selection, show input for phone or email, or qr code for app.
  - Verification code is sent once user fills in phone/email, or available in app once qr code is scanned.
  - User inputs verification code from phone/email/app.
  - If code is correct, user is considered registered for MFA and will be prompted on future sign in attempts.
### Validation
- Sign in page stays the same.
- On sign in attempt, if user has MFA enabled and their email/password is valid, they'll be redirected to a MFA Validation page
- MFA Validation page
  - User selects one of their enabled MFA factors from a dropdown
  - Verification code is sent once factor selected (for phone or email; not needed for app-based)
  - Help text prompts user to check their phone/email/app, and user enters code.
  - If code is correct, user is signed in and authentication is complete.

## Models
Twilio handles code generation and secret storage, so we would just have to keep track of which users have which factors enabled. I'm thinking a model/table like this:
- authentication_factors
    - id
    - user_id (fk to associated user)
    - type (e.g. sms, app, email)
    - external_id (e.g. the factor_id required by Verify for TOTP)
    - email or phone? (or we can just get that from user)
    
## Code
Registration is pretty straightforward. We can add a new controller and views for various actions on authentication_factors.

Validation on sign in is trickier since we have to override some devise behavior. [This example](https://www.honeybadger.io/blog/multi-factor-2fa-authentication-rails-webauthn-devise/) overrides the devise SessionsController's `create` action to redirect to a new MFA controller/views, using the session to keep track of the user id. If tokens are valid once the user has gone through the 2FA process on that page, this new controller signs in the user. I was able to get a more generic version of that working locally and it seems fairly simple and effective. I'd want to test more edge cases for security concerns though.

**Comment by djohnston32** [comment]
I think it'll be best to implement one factor at a time, so I'm going to start with SMS unless there's a strong preference for something else first. No given type seems way easier or harder than another so no strong feelings on my side.

If you feel good about Verify, can you make a Verify Service for me to test with at [this link](https://www.twilio.com/console/verify/services)? No rush though, I can make progress with mocked versions of all the calls for now.

**Comment by colinxfleming** [comment]
the model change looks right to me. we don't store phones for CMs in our db currently; bonus if that column is scrambled. (I feel like rails 7 might have some nice stuff around this though I can't remember super clearly.)

The UI/controller/view changes also seem right to me but @lomky has thought about this harder than I have so that opinion goes!

I spun up a verify service; I'll send you the details for it offthread. thanks @djohnston32 !

**Comment by djohnston32** [comment]
The first one is the one I have immediate thoughts on:
    * Maybe an enable/disable switch on each factor, plus a delete button for each. Then an "enable/disable all" switch plus a "delete all" button. That would offer full control, but may be a bit too complicated.
    * Might be simpler to make it so disabling just means deleting, and if a factor exists that means it's enabled. I think I like this approach the most for offering a good balance of control and simplicity.
    * The simplest way would be only having "disable all" like you said. I totally agree, good messaging would be key there. 
    * I think the best way to allow changing is to require deleting one factor and adding another. I feel like a dedicated change operation would add too much complexity.
    * From an implementation perspective there's no need for the number of factors or number of each type to be limited. But we could add limits if desired.
    * This could all exist on the Edit Profile page, or the Profile could link to a dedicated two factor settings page (e.g. `/users/1/authentication_factors`)

**Comment by colinxfleming** [comment]
I think for a v1 of this the more we err on the side of simplicity the better. So 'only one active option' + 'deleting = disabling' sounds good to me if we think that's simpler from a user perspective? Agree with @lomky that the rest of this sounds great. Let us know if you need to resolve anything else to get cooking!

**Comment by djohnston32** [comment]
Sounds good! Work is in progress focusing just on SMS. I got the basic skeleton of controllers/views in place last week with all the API calls mocked. I've been using the [wicked](https://github.com/zombocom/wicked) gem for multi-step forms and I like the way that's feeling. This week I'm adding in more validations and error handling, etc, then I'll plug in the real API. Aiming to have a PR up by the end of the week.

**Comment by djohnston32** [comment]
Uploaded my changes so far to a [remote branch](https://github.com/djohnston32/dcaf_case_management/tree/dhj/mfa-sms). If you run locally you can see the rough registration and login flows with SMS-only. All the Twilio API calls are mocked so you just have to put in '111111' as the verification code whenever asked and it works. 2FA registration can be found on the Edit Profile page.

No pressure to look now though, especially not to review in depth at this point since there will be an actual PR coming later. I still have to add the actual API, refine the UI styles and text, add some more robust error handling, add tests, etc. to get it production ready. Just wanted to put it out there.

**Comment by xmunoz** [comment]
I think we can declare victory on this.
