### ISSUE TITLE
Singleton Configs act funny with commas

### ISSUE THREAD

**Issue by elimbaum** [DARIAEngineering/dcaf_case_management#2194]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Parse singleton values (integers, URLS, etc) in configs.

* **What feature or behavior is this required for?**
Budget bar, archive days (upcoming), URL handling, few other single-word configs.

* **How could we solve this issue? (Not knowing is okay!)**

Even though the help text says to enter numbers without commas, if you do enter a comma (i.e. budget bar max = `10,000`), it seems like that's being interpreted as a list (so budget bar max = `[10, 0]`). This *is* the expected behavior given the current code, so it's not really a bug, but it may make sense to add validation for singleton values versus things that _could be_ a list.

This also applies to URLs, start of week, hide practical support, etc... if you enter `https://cats,dogs.com` as a URL, it will _successfully validate_ and turn into `https://dogs.com` because the URL handling code calls `options.last`. I would argue that, given that input, we should fail to validate, rather than succeed in the way we are. (I could see this happening in practice with a minor typo: `sub.domain.com => sub,domain.com => domain.com`)
 
* **Anything else?**

I know this could make things more complicated because it will bifurcate our config handling. So may not be a priority issue; just came across it while adding new config fields.

**Comment by colinxfleming** [comment]
I think this does make things a little more complicated, but also this is a way that people can currently bust the application. So it probably is worth putting a little extra elbow grease in here.

That said, you yourself wrote a pretty impressively robust validation engine in config, so I think this might be more straightforward than it appears. Why not make these changes?

* in `VALIDATIONS`, it's `config_key: :validator_func` right now. Why not make the validator func an of validator funcs, like `budget_bar_max: [:validate_number, :validate_no_commas]`?
* Then I think we'd make a place change to the `validate_config` method to take an array rather than just a single symbol.
* Then we'd definite the commas validation you outline above.

What do you think, does that seem reasonable?

**Comment by elimbaum** [comment]
that's a great point! I can add this in next.
