### ISSUE TITLE
Budget Bar doesn't accurately reflect money sent

### ISSUE THREAD

**Issue by elimbaum** [DARIAEngineering/dcaf_case_management#2757]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Accurately display funds sent on budget bar. If amount sent by fund does not equal pledged, budget bar still lists the *pledged* amount as being sent. Maybe this is a reallllllllly funky edge case, but I think it's incorrect behavior that we could improve.

* **What feature or behavior is this required for?**

Budget bar

* **How could we solve this issue? (Not knowing is okay!)**

Better validation, and maybe change which value is displayed on budget bar.

* **Anything else?**

pics ->

ex... we pledge $52. we send $60.

<img width="404" alt="Screen Shot 2022-11-22 at 17 29 05" src="https://user-images.githubusercontent.com/7085805/203434644-71548914-b6ad-493d-9c40-eab2e417197e.png">

but budget bar says we sent $52! this is true in the reverse (sent < pledged). i don't know a ton about budget bar usage but this feels incorrect?

<img width="313" alt="Screen Shot 2022-11-22 at 17 29 10" src="https://user-images.githubusercontent.com/7085805/203434678-6754c09f-0f70-457e-bf3b-c9a74cfdbb56.png">

**Comment by colinxfleming** [comment]
I think I can clear this up - the tricky part here is the disambiguation between pledge money, sent money, and fulfilled money. I'm using ecommerce here as a rough metaphor.

* Pledged money is money set aside when working with a patient for their abortion care. It represents a sort of pending state, as if it were in a shopping cart but not officially given to the recipient clinic yet. This shows up on the budget bar in yellow/orange.
* Sent money is money guaranteed to a clinic when working with a patient. It represents a promise to a clinic to hit them back for however much money. While this doesn't hit a fund's bank account, it's generally how funds keep track of money out the door, and how they keep track of debits to their bank account. This is _roughly_ analogous to when you buy something on a credit card and it's in a pending state for a few days -- some stuff is working itself out but you can generally consider that money spent. This shows up on the budget bar as green.
* Fulfillment money, in that first screenshot, is kinda different -- the fulfillment process is generally that some amount of time after abortion care (usually 4-6 weeks), a clinic sends a remit back to the fund to tell them to make good on the pledge. (This is, like, roughly equivalent to it showing up on your credit card bill.) At that point the accountant generally cuts the fund a check; the amount of that check allocated for a particular patient is the Fund Payout. Since this doesn't happen until clinics get around to sending remits, it can be a few weeks, and happens outside the regular flow of case management. As such, we don't represent fund payout on the budget bar, just pledge amounts.

Let me know if that makes sense!

**Comment by elimbaum** [comment]
cool, that makes sense. i never really paid attention to government contracting but i think we had some equivalent a la commit/obligate/expend etc.

> As such, we don't represent fund payout on the budget bar, just pledge amounts.

so, this is not a bug, correct? if so i'll close.

**Comment by colinxfleming** [comment]
yep, gov contracting expenditures are probably a similar analog! Not a bug, expected behavior.
